### ISSUE TITLE
Running example("MultiAssayExperiment")

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/biocMultiAssay#100]
@mtmorgan @vjcitn @lwaldron 

It would be a nice feature to have if one could just call 
```
example("MultiAssayExperiment")
```
and get the toy dataset example back. 

I'm not sure how to set this up. Any insight would be helpful. 
It seems like it would go under `@examples` for the MultiAssayExperiment

Regards,
MR

**Comment by vjcitn** [comment]
Isn't it sufficient to put the example in the Rd file that has
\alias{MultiAssayExperiment} ?

**Comment by LiNk-NY** [comment]
Yes, thank you Vince. 
Using roxygen I can add it like this: 
```
@example /path/to/file/example.R
```
