### ISSUE TITLE
Get rid of fill=TRUE option to subsetBySample(), implement as a function for MultiAssayExperiment class

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#53]
create a fill method that fills missing assay data with columns of NAs.  No need yet to add an argument to the MultiAssayExperiment() constructor.

**Comment by lwaldron** [comment]
On second thought, just implement this as a method for MultiAssayExperiment class.  Would be easy then to add as an argument to the constructor later.

**Comment by lwaldron** [comment]
subsetBySample() currently broken in biocMultiAssayToyExample.Rmd vignette - should be fixed when removing filling from subset operation.

**Comment by LiNk-NY** [comment]
Adding a column to the existing objects requires a lot of object-specific function knowledge. For example, adding an NA column to an ExpressionSet would require modification of the pData as well as the exprs. This method can complicate supporting other types of objects (i.e. SQL connection objects). I am wondering if this is the way we want to account for missing values in the data? 

@mtmorgan 
@vjcitn

**Comment by lwaldron** [comment]
There is no accounting problem with the missing data for a patient on some assays, so maybe missing columns should instead be dealt with if/when the numeric data are extracted for analysis? I'm no longer clear on the rationale for wanting to fill in missing columns for the stored object.

**Comment by lwaldron** [comment]
I guess this would involve requiring each allowed class for assays support a method such as: 


```r

addCols  <- function (obj, newcolnames="character")

```

which would not be so bad for the current supported classes, but I'm not sure about complex classes we might want to add.

**Comment by LiNk-NY** [comment]
obsolete
