### ISSUE TITLE
simplify the verbs

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#56]
Instead of implementing new methods for our verbs `subsetFeature`, `subsetSample`, `sampleExtractor`, and `featExtractor` for every supported assay class, implement methods as needed for the assay class. 

For example, 
* instead of the current `setMethod("featExtractor", etc)` in [R/biocMultiAssay-methods.R](https://github.com/vjcitn/biocMultiAssay/blob/master/R/biocMultiAssay-methods.R), 
* for each supported class, use `setMethod("rownames", etc)` as needed so that you can use rownames on each of these classes.
* will have to decide which is the right function to use so as not to conflict with existing definitions - rownames might not be the right choice, as I see rownames(grl[[1]]) already works but returns null.  

@mtmorgan does this sound right to you?

**Comment by mtmorgan** [comment]
Yes, that's the gist of my suggestion.

**Comment by LiNk-NY** [comment]
`features` and `samples` words used for the extraction methods
The subset method names remain the same
