### ISSUE TITLE
Class capitalization

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#61]
Cllass names should be CamelCase, e.g., [Stage](https://github.com/vjcitn/biocMultiAssay/blob/master/R/stage-class.R#L24)

**Comment by lwaldron** [comment]
Thanks Martin.  Should stage() function stay lower-case, or capitalize it as well?

**Comment by kasperdanielhansen** [comment]
Constructor classes should be capitalized. 

Best,
Kasper
(Sent from my phone.)

**Comment by lwaldron** [comment]
So this includes `Elist` and the `Elist()` constructor/accessor.

**Comment by LiNk-NY** [comment]
Classes capitalized.
