### ISSUE TITLE
.checkElist2 validity check

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#62]
Not sufficient that elist is the same length as sampleMap assaynames - elist names must be the same as the string of unique sampleMap assaynames (if both are sorted).

But what if no samples are left for one assay and drop=FALSE? I _think_ the answer is to only check the names of elist elements with more than zero samples.

**Comment by LiNk-NY** [comment]
A less strict criteria for experiment names in the MultiAssayExperiment is currently in place. All experiment names in the MultiAssayExperiment must be found in the sampleMap assaynames. 
https://github.com/vjcitn/biocMultiAssay/blob/master/R/MultiAssayExperiment-class.R#L76

**Comment by lwaldron** [comment]
Agreed, this is sufficient.
