### ISSUE TITLE
change masterPheno slot/extractor to specimenData?

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#63]
or similar?  This was a request from an audience member at EuroBioc, not to use parts of the word "phenotype" to refer to specimen / sample data, which may include things like treatment that are not phenotype.  Would be nice to get any more thoughts about this naming.

**Comment by vjcitn** [comment]
I like the change proposed.

**Comment by kasperdanielhansen** [comment]
The counterargument is that we have a lot of baggage using pheno data.
Absolutely true that the term is imprecise, but I am not sure that this is
enough to justify adding additional confusion with a new term.

**Comment by LiNk-NY** [comment]
It would certainly be more convenient to keep "masterPheno" as the accessor/slot name but I wouldn't be against changing it. Do you suggest we use "phenoData" instead? @kasperdanielhansen

**Comment by ttriche** [comment]
the fall and rise of phenoData!

+1 for salvaging this keyword 

--t

**Comment by kasperdanielhansen** [comment]
Unsure whether I like pData or phenoData more.  Both has been in use, with
pData being more used because it returns a data.frame unlike the
AnnotatedDataFrame you get from phenoData.

**Comment by kasperdanielhansen** [comment]
I would tend to use pData, I must say.

**Comment by ttriche** [comment]
point taken, I had forgotten there was a difference (and I usually add a
canonical covariates() method which is called by pData/colData, similar to
features() called by fData/rowRanges).

Most of the time what people actually want is that data.frame or DataFrame.


--t

**Comment by lwaldron** [comment]
I kind of like pData due to force of habit, and if someone complains about imprecise use of the word phenotype, we could claim it stands for "primary data" in this case...

**Comment by lwaldron** [comment]
Yes, change to pData.
