### ISSUE TITLE
elist-class.R : .checkMethods outdated

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#64]
requires "[" but it is subsetFeature() and subsetSample() that are used on elist elements.

**Comment by vjcitn** [comment]
I hate to be picky about names.  But subsetByFeatures and subsetBySamples
seem the appropriate
phrases for operating on a MultiAssayExp -- subsetFeature sounds like
something that might
extract exons from a gene model ... to me, at least.

**Comment by lwaldron** [comment]
Lots of discussion over names here - also with Martin and others. It is also not to late to consider something radical like just using rownames, colnames, subsetRow, subsetCol. 

**Pros:**
* It would make incorporation of additional data classes even easier
* The usual contract that rownames() and colnames() return a character vector is exactly what we want
* apparently features() and samples() isn't as obvious to everyone as it is to me

**Cons:**
* `rownames(MultiAssayExperiment)` would break that usual contract and return a list of character vectors

**Comment by ttriche** [comment]
having rownames()/rowRanges() and colnames() return a list is a GOOD thing:
it will cause code that assumes a matrix (instead of a tensor) to fail.



--t

**Comment by vjcitn** [comment]
I am in favor of reusing the conventional names whenever suitable, and the conventions
can be driven by the primary container type in use now, which is RangedSummarizedExperiment.
elist elements must thus answer to rowRanges (or rownames, but names?), colnames, colData, assay, [; the latter handles feature or sample selections.  Do we need anything else?

for the MultiAssayExperiment, subsetBySamples is obvious, and subsetByFeatures could take
a named list, with names drawn from the elist names, and selections as relevant for
each element.  These are both endomorphisms -- for now, although this inductive construction
of a selection in multiple stages is also attractive, and a Stage instance seems to be another
possible input to [ or the subsetting methods.

**Comment by lwaldron** [comment]
The key operations we'll need for manipulation are equivalent to rownames/colnames/"["/assay. If we use these, by my probably incomplete tally we'll need to define the following for base classes:

`RangedSummarizedExperiment`: none
`GRangesList`: rownames, colnames, "[", assay. "[" would only be defined for character arguments before and after comma.
`matrix`: assay
`ExpressionSet`: assay

For the MultiAssayExperiment, the `subset(myMA, method="samples")` seems intuitive, and can call the `Stage()` function first so that the subset function that does the real work always acts on a `Stage` object.

**Comment by lwaldron** [comment]
PS thanks Tim.  For me it also seems good for rownames(myMA) to return a list.

**Comment by LiNk-NY** [comment]
The `subsetFeature()` and `subsetSample()` methods use the `[` method to do the subsetting. Those methods were created to make it easier to subset by different combinations of classes.
