### ISSUE TITLE
colnames RaggedRangedAssay

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/biocMultiAssay#66]
I can't seem to figure out why the colnames method for RaggedRangedAssay class isn't working in the vignette. The show method for the Elist is displaying 0 samples 0 features.  
If I run the code interactively, it works and I get the colnames back. [A gist is located here](https://gist.github.com/LiNk-NY/1d3c47967dbf6b9b1995). 

Your help is appreciated. 
MR

@vjcitn 
@lwaldron 
@mtmorgan

**Comment by mtmorgan** [comment]
Add

    imports(BiocGenerics)

to the NAMESPACE file, otherwise show finds base::colnames; I'm not 100% sure why.

**Comment by LiNk-NY** [comment]
That solved it. Thanks!
