### ISSUE TITLE
Constructors should work without arguments, and return an object of the appropriate class

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#67]
For instance, `RaggedRangedAssay()` should work but does not

```
> RaggedRangedAssay()
Error in RaggedRangedAssay() : argument "x" is missing, with no default
```

Usually (though not always), this _simplifies_ the implementation, even though the first thought is that the zero-length constructor will require some kind of conditional code / additional method implementation.

A generic should as a general rule have a contract that the return value is consistent across methods. In particular a constructor should return an object of the corresponding class. This is not the case for `RaggedRangedAssay(list())`, which returns a simple list

```
is(RaggedRangedAssay(list()), 'RaggedRangedAssay')   # FALSE
```

**Comment by LiNk-NY** [comment]
Hi @mtmorgan, 
setMethod("RaggedRangedAssay", signature("missing"), function(x) new("RaggedRangedAssay"))
would do the trick. Is there a preference over having this over conditional code for creating an empty class object? 
This method seemed more straightforward to me. Thanks!

**Comment by lwaldron** [comment]
This addresses the first issue that @mtmorgan raised, but not the second - that `RaggedRangedAssay()` should not return an object of any class other than RaggedRangedAssay.

**Comment by LiNk-NY** [comment]
Yes, I removed the RaggedRangedAssay method for lists and expanded the helper function for converting GRLs to RRAs.

**Comment by mtmorgan** [comment]
One thing about conditional code in a plain old function is that one goes through a 'funnel' toward a call to the class generator (I like `.A = setClass("A", ...); .A(...)` rather than calling `new("A", ...)`) and object construction; where complex constraints or class requirements can be enforced / computed at the narrow end of the funnel, before the call to `.A()`. What generally happens with multiple methods is that they each call `.A()` independently, so the code for satisfying class requirements gets duplicated; an acceptable pattern is where the methods implement a 'facade' that do preliminary processing, and then hand a consistent set of objects to a single function that does whatever complexity is required and calls the class generating function.

**Comment by lwaldron** [comment]
How about this (I'm sure my syntax isn't quite right, but the idea):

```
setMethod(RaggedRangedAssay, signature="GRangesList", function(...){
  as(grl, "RaggedRangedAssay")
})
setMethod(RaggedRangedAssay, signature="ANY", function(...){
  grl=GRangesList(...)
  RaggedRangedAssay(grl)
})
```

**Comment by LiNk-NY** [comment]
In the case of the `Elist`, how do you differentiate between a generic function and a builder function of the same name? 
I have implemented the framework that you suggested here but when I call Elist(), I get an error:  
> Error in S4Vectors::SimpleList(x) : 
  argument "x" is missing, with no default 
because it is referring to the `Elist` generic function rather than the builder. 

https://github.com/vjcitn/biocMultiAssay/blob/renames/R/Elist-class.R#L47

**Comment by lwaldron** [comment]
I think the builder function has to be a method for the generic function, for signature="ANY".

**Comment by LiNk-NY** [comment]
Elist method can dispatch on "ANY" and "missing" signatures. Thanks!
