### ISSUE TITLE
"assay" method for RaggedRangedAssay

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/biocMultiAssay#68]
For the ExpressionSet class, assay would return Biobase::exprs(ExpressionSet)
For a matrix class, it returns the identity, just (matrix).  
@mtmorgan @vjcitn @lwaldron 
What should the assay method return for signature RaggedRangedAssay?

**Comment by vjcitn** [comment]
On Tue, Dec 15, 2015 at 1:33 PM, Marcel Ramos <notifications@github.com>
wrote:

> For the ExpressionSet class, assay would return
> Biobase::exprs(ExpressionSet)
> For a matrix class, it returns the identity, just (matrix).
>
> @mtmorgan <https://github.com/mtmorgan> @vjcitn
> <https://github.com/vjcitn> @lwaldron <https://github.com/lwaldron>
> What should the assay method return for signature RaggedRangedAssay?
>

Do we have an example of this?  It seems to me that after a small number of
exemplars, you leave it to the creator of the class to define an assay
method
that conforms to the API.  I haven't seen a RaggedRangedAssay -- is it
MultiAssayExperiment-specific?

**Comment by LiNk-NY** [comment]
It's the wrapper for the GRangesList class created to add methods to the GRangesList without modifying the GRL API. 
setClass("RaggedRangedAssay", contains = "GRangesList")

**Comment by vjcitn** [comment]
I don't know exactly what's intended but after

library(GenomicRanges)
example(GRangesList)

> do.call(rbind, lapply(grl, mcols))

DataFrame with 5 rows and 2 columns

      score        GC

  <integer> <numeric>

1         5      0.45

2         3      0.30

3         4      0.50

4         6      0.40

5         2      0.10


seems like a step towards an assay method.

**Comment by LiNk-NY** [comment]
Change added.
