### ISSUE TITLE
Wanted: NSBS error after callNextMethod

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/biocMultiAssay#69]
@mtmorgan @vjcitn @lwaldron 
Hi all, 
I am trying to use the inherited `GRangesList` subset functionality of the "i" argument in `grl[i, j, ..., drop]` as the "j" argument in the RaggedRangedAssay since those are the `colnames`. 
What this would do is provide the all too familiar NSBS error mechanism when invalid names are entered for subsetting. 
So far, I'm getting an empty list rather than an error. 

Perhaps I am a bit unclear on how callNextMethod works?

Here is the gist: 

[https://gist.github.com/LiNk-NY/510937a62b1202397b4b](https://gist.github.com/LiNk-NY/510937a62b1202397b4b)
Thank you!

Regards, 
Marcel

**Comment by mtmorgan** [comment]
At https://github.com/vjcitn/biocMultiAssay/blob/renames/R/biocMultiAssay-methods.R#L108 j = character(0), so callNextMethod is the same as grl[character(0)]

**Comment by LiNk-NY** [comment]
Thanks!
