### ISSUE TITLE
make use of accessors() in internal code

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#75]
e.g., here
https://github.com/vjcitn/biocMultiAssay/blob/master/R/MultiAssayExperiment-class.R#L40  use sampleMap(). Many updates throughout.

**Comment by lwaldron** [comment]
MultiAssayView-class.R (will be modified)

**Comment by LiNk-NY** [comment]
Adding fd94bc8 addresses this issue.
