### ISSUE TITLE
Avoid comparison of class names using `==`

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#78]
E.g., https://github.com/vjcitn/biocMultiAssay/blob/renames/R/Elist-class.R#L13. This can be problematic when the object is an S3 class (character() of length > 1, so if() fails). Instead, use `inherits(object, "Foo")` or `is()`.

**Comment by lwaldron** [comment]
e.g. MultiAssayExperiment.R, line 39.

**Comment by LiNk-NY** [comment]
using inherits(object, "GRangesList") in line 39

**Comment by kasperdanielhansen** [comment]
Question: I have always used is(), but should I use inherits()? What is the
difference?

Best,
Kasper

**Comment by mtmorgan** [comment]
?inherits says

     The analogue of 'inherits' for formal classes is 'is'.  The two
     functions behave consistently with one exception: S4 classes can
     have conditional inheritance, with an explicit test.  In this
     case, 'is' will test the condition, but 'inherits' ignores all
     conditional superclasses.

which suggests that yes, is() is somehow more flexible. I can't believe that the complicated inheritance where the different occurs is actually useful.

**Comment by kasperdanielhansen** [comment]
And it seems that inherits is faster, according to ?is.  I didn't even know
about conditional inheritance and it is explicitly discourage so I'll
switch to inherits I think.
