### ISSUE TITLE
Stage() is really MultiAssayView() constructor

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#81]
Rename `Stage()` as `MultiAssayView()`. 

Replace identifier / method arguments with assay, rownames, colnames. Process in "most useful" order.

Similarly for subset,MultiAssayExperiment-method.

Represent MultiAssayExperiment with slots containing names of assays, featurenames, samplenames.

Subset updates slots.

First step: create a mock-up

**Comment by LiNk-NY** [comment]
I took care of the renaming part of this.
