### ISSUE TITLE
setReplaceMethod

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/biocMultiAssay#83]
@mtmorgan @vjcitn @lwaldron 

I'm trying to use a replacement method for the MultiAssayExperiment but I keep getting an error that says "function<-" not defined. Here is what I have included. 

setReplaceMethod("sampleMap", c("MultiAssayExperiment", "DataFrame"),
                 function(x, value) {
                   slot(x, "sampleMap") <- value
                   return(x)
                 })

Error: no existing definition for function 'sampleMap<-'

Do I have to create a generic? 
I'm not familiar with this type of method. 
Thank you.

**Comment by ttriche** [comment]
```
setGeneric("sampleMap<-", function(object, ..., value) {
  standardGeneric("sampleMap<-")
})
```
then go about your business

--t

**Comment by ttriche** [comment]
```
setGeneric("sampleMap<-", function(object, ..., value) {
  standardGeneric("sampleMap<-")
})
```
then go about your business

**Comment by LiNk-NY** [comment]
Got it, thanks!
