### ISSUE TITLE
use vapply() where appropriate

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#86]
Use most appropriate function, e.g., vapply() instead of unlist(lapply()). E.g.,

https://github.com/vjcitn/biocMultiAssay/blob/master/R/biocMultiAssay-methods.R#L178

**Comment by LiNk-NY** [comment]
Vapply implemented in [9dba911](https://github.com/vjcitn/biocMultiAssay/commit/9dba9116bb063c28507f1e8db9746241cb9168e5)
