### ISSUE TITLE
format user facing code chunks as validate / do / return

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/biocMultiAssay#87]
Probably the right pattern is to check inputs (all) then process.

```
if (!is.character(foo))
    stop("'foo' must be character")
## now do processing foo
```

This way, the processing steps are not nested deeply in the function body

https://github.com/vjcitn/biocMultiAssay/blob/master/R/subsetByRow.R#L11

**Comment by LiNk-NY** [comment]
Function made into generic and method 10a7278
