### ISSUE TITLE
make subset*() functions generic

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#91]
subsetByAssay: character, logical, integer
subsetByColumn: character, logical, integer
subsetByRow: character, GRanges (GRanges to be implemented)

**Comment by LiNk-NY** [comment]
Should I include methods for each type or just one method for signatures `c("MultiAssayExperiment", "ANY")`?

**Comment by lwaldron** [comment]
I think methods for each type, with one as the workhorse method, and others translate to that signature then call it.

**Comment by LiNk-NY** [comment]
added in 10a7278
