### ISSUE TITLE
republish rpubs document

### ISSUE THREAD

**Issue by LiNk-NY** [vjcitn/biocMultiAssay#95]
@lwaldron 
Re-run and republish toy vignette at [rpubs](http://rpubs.com/lwaldron/biocmultiassaytoyexample)

**Comment by lwaldron** [comment]
Done, with substantial improvements to the vignette.  Removed all references to MultiAssayView, which can be demonstrated in a separate vignette - this one will be for beginners. Vignette renamed from biocMultiAssayToyExample.Rmd to MultiAssayExperiment.Rmd. See changeset [0ef3154](https://github.com/vjcitn/biocMultiAssay/tree/0ef31547811fc691f0db715eb098b366a60d88cf) for prior version of vignette.
