### ISSUE TITLE
Why is toListMap() exported, and .convertList() not?

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/biocMultiAssay#97]
It seems like `.convertList()` is more likely to be wanted by the user, as it converts a list object into a three-column DataFrame that can be used for the sampleMap, and is even used for this purpose in the biocMultiAssayToyExample vignette.  The reverse operation, `toListMap()`, might be useful for some other reason but I can't think offhand of why.  What is the rationale?

**Comment by LiNk-NY** [comment]
No particular reason. I will fix this. Thanks

**Comment by lwaldron** [comment]
makeMap sounds good to me.

**Comment by lwaldron** [comment]
Actually, how about listToMap(), a little more descriptive.

**Comment by LiNk-NY** [comment]
Sounds good
